
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Services
{

using System;
    using System.Collections.Generic;
    
public partial class ThongTinChuyenDi
{

    public int stt { get; set; }

    public string MaChuyen { get; set; }

    public string MaTX { get; set; }

    public string TenTX { get; set; }

    public string MaHDV { get; set; }

    public string TenHDV { get; set; }

    public string MaCX { get; set; }

    public string TenDD { get; set; }

    public Nullable<System.DateTime> NgayBatDau { get; set; }

    public Nullable<System.DateTime> NgayKetThuc { get; set; }

}

}
